### ISSUE TITLE
Posar cada assignatura amb el seu propi fitxer

### ISSUE THREAD

**Issue by raulgilabert** [hwfib/hwfib.github.io#16]
En referència a la issue #11 he pensat que ens pot generar problemes a l'hora de incloure les noves o fer modificacions mentre un altre també escriu. Per evitar conflictes crec que el millor seria tenir un fitxer per cada assignatura i ja després que al fer el deploy jekyll o fiqui tot en un sol HTML

**Comment by rdvdev2** [comment]
M'hi poso quan tinguem merge de #22
