### ISSUE TITLE
Utilitzar un template engine

### ISSUE THREAD

**Issue by rdvdev2** [hwfib/hwfib.github.io#5]
Tot i que m'agrada la idea d'utilitzar pur HTML, crec que no estaria de més generar aquest amb un template engine per així no tenir tanta repetició amb les capçaleres i els footers. De cara a l'usuari seguiria sent pur HTML, només hi hauria un pas de preprocessat previ al deployment (GH Actions FTW). L'elecció del engine concret crec que és una pregunta a part, primer s'hauria de decidir si es vol algun o no.

**Comment by raulgilabert** [comment]
Crec que és el millor

**Comment by Serikpg** [comment]
Okayy... Super, per molt que es perdi una mica el sentit... Si us ocupeu de canviar-ho tot lo  escrit per mi 10/10.
I quin podriem utilitzar??

**Comment by raulgilabert** [comment]
> Okayy... Super, per molt que es perdi una mica el sentit... Si us ocupeu de canviar-ho tot lo escrit per mi 10/10. I quin podriem utilitzar??

no crec que perdi el sentit, la idea es que de cara a l'usuari sigui simple, això no implica que de cara a nosaltres ens hagi de dificultar amb treball innecessari el modificar la web. Ara perque és petit però si en un futur tenim moltes més pàgines y volem fer una modificació al menú de navegació haurem d'editar tots els fitxers, que pot provocar que ens deixem algun i hagi diferències que no haurien d'haver

Respecte a la proposta crec que lo millor podria fer servir Jekyll que és totalment compatible amb GitHub Pages

**Comment by Serikpg** [comment]
Siii, de fet ja vam parlar sobre Jekyll... si pots mirar-t'ho tu i fes el pas d'HTML a Jekyll... Abans però us faig el PR de la branca on tenia el tema d'assignatures començat.

**Comment by rdvdev2** [comment]
Em mola la idea de Jekyll, senzill i molt ben integrat

**Comment by rdvdev2** [comment]
M'ocupo d'aixó
